"""corrected migrate total_count_view total_count_skip to HabitTracking

Revision ID: 05e21d7eea19
Revises: 647bd025697b
Create Date: 2024-03-19 09:08:54.952977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '05e21d7eea19'
down_revision: Union[str, None] = '647bd025697b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habittrackings', 'total_count_view',
                    existing_type=sa.INTEGER(),

                    default=0)
    op.alter_column('habittrackings', 'total_count_skip',
                    existing_type=sa.INTEGER(),

                    default=0)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habittrackings', 'total_count_skip',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('habittrackings', 'total_count_view',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
