"""Added total_count_view total_count_skip to HabitTracking

Revision ID: 647bd025697b
Revises: 6134528d0045
Create Date: 2024-03-19 09:00:58.353116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647bd025697b'
down_revision: Union[str, None] = '6134528d0045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habittrackings', sa.Column('total_count_view', sa.Integer(),
                                              nullable=False,
                                              default=0))
    op.add_column('habittrackings', sa.Column('total_count_skip', sa.Integer(),
                                              nullable=False,
                                              default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habittrackings', 'total_count_skip')
    op.drop_column('habittrackings', 'total_count_view')
    # ### end Alembic commands ###
